//packages
export const GET_TRAVELPACKAGES = "GET_TRAVELPACKAGES";
export const GET_TRAVELPACKAGEDETAIL = "GET_TRAVELPACKAGEDETAIL";
export const TRAVELPACKAGES_LOADING = "TRAVELPACKAGES_LOADING";

export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const CHECKOUT = "CHECKOUT";

//user
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";

//errors
export const SET_ERRORS = "SET_ERRORS";

//reviewss
export const GET_USER_REVIEW = "GET_USER_REVIEW";
export const GET_TRAVELPACKAGE_REVIEWS = "GET_TRAVELPACKAGE_REVIEWS";
export const POST_REVIEW = "POST_REVIEW";

export const TRIGGER_UPDATING_LIST = "TRIGGER_UPDATING_LIST";
export const FINISH_UPDATING_LIST = "FINISH_UPDATING_LIST";

export const GET_TRAVELPACKAGESONLY = "GET_TRAVELPACKAGESONLY";

export const TRAVELPACKAGEDETAIL_LOADING = "TRAVELPACKAGEDETAIL_LOADING";
export const BOOKINGDETAIL_LOADING = "BOOKINGDETAIL_LOADING";
export const PROFILE_LOADING = "PROFILE_LOADING";

export const GET_USER_REVIEWS = "GET_USER_REVIEWS";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const GET_BOOKINGS = "GET_BOOKINGS";
export const GET_BOOKING_DETAIL = "GET_BOOKING_DETAIL";
