//packages
export const GET_TRAVELPACKAGES = "GET_TRAVELPACKAGES";
export const GET_TRAVELPACKAGEDETAIL = "GET_TRAVELPACKAGEDETAIL";
export const TRAVELPACKAGES_LOADING = "TRAVELPACKAGES_LOADING";

export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const CHECKOUT = "CHECKOUT";
export const BOOKINGS = "BOOKINGS";

//user
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";

//errors
export const SET_ERRORS = "SET_ERRORS";

//reviewss
export const GET_USER_REVIEW = "GET_USER_REVIEW";
export const GET_TRAVELPACKAGE_REVIEWS = "GET_TRAVELPACKAGE_REVIEWS";
export const POST_REVIEW = "POST_REVIEW";
